version: '3'

services:
  web_app:
    build: ./web_app
    container_name: web_app_socnet
#    env_file: ./web_application/web.env
    command: /code/run_web.sh
    volumes:
      - ./web_app:/code
    ports:
      - "8001:8000"
